-- MySQL Script generated by MySQL Workbench
-- vie 09 jul 2021 18:10:25 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`T_Owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`T_Owner` ;

CREATE TABLE IF NOT EXISTS `mydb`.`T_Owner` (
  `user_owner` VARCHAR(45) NOT NULL,
  `name_owner` VARCHAR(45) NULL,
  `mail_owner` VARCHAR(45) NULL,
  `mail_manager` VARCHAR(45) NULL,
  PRIMARY KEY (`user_owner`))
ENGINE = InnoDB
COMMENT = 'Tabla que almacena la información del propietario de la base de datos';


-- -----------------------------------------------------
-- Table `mydb`.`T_Clasifica_Calif`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`T_Clasifica_Calif` ;

CREATE TABLE IF NOT EXISTS `mydb`.`T_Clasifica_Calif` (
  `id_Clasifica_Calif` INT NOT NULL AUTO_INCREMENT,
  `clasifica_calif` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Clasifica_Calif`))
ENGINE = InnoDB
COMMENT = 'Tabla con los criterios de clasificación';


-- -----------------------------------------------------
-- Table `mydb`.`T_Info_DB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`T_Info_DB` ;

CREATE TABLE IF NOT EXISTS `mydb`.`T_Info_DB` (
  `bd_name` VARCHAR(45) NOT NULL,
  `T_Owner_user_owner` VARCHAR(45) NOT NULL,
  `confidenciality` INT NOT NULL,
  `integrity` INT NOT NULL,
  `availability` INT NOT NULL,
  `clasification` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bd_name`, `T_Owner_user_owner`, `confidenciality`, `integrity`, `availability`),
  INDEX `fk_T_Info_DB_T_Owner_idx` (`T_Owner_user_owner` ASC),
  INDEX `fk_T_Info_DB_T_Clasifica_Calif1_idx` (`confidenciality` ASC),
  INDEX `fk_T_Info_DB_T_Clasifica_Calif2_idx` (`integrity` ASC),
  INDEX `fk_T_Info_DB_T_Clasifica_Calif3_idx` (`availability` ASC),
  CONSTRAINT `fk_T_Info_DB_T_Owner`
    FOREIGN KEY (`T_Owner_user_owner`)
    REFERENCES `mydb`.`T_Owner` (`user_owner`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_Info_DB_T_Clasifica_Calif1`
    FOREIGN KEY (`confidenciality`)
    REFERENCES `mydb`.`T_Clasifica_Calif` (`id_Clasifica_Calif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_Info_DB_T_Clasifica_Calif2`
    FOREIGN KEY (`integrity`)
    REFERENCES `mydb`.`T_Clasifica_Calif` (`id_Clasifica_Calif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_Info_DB_T_Clasifica_Calif3`
    FOREIGN KEY (`availability`)
    REFERENCES `mydb`.`T_Clasifica_Calif` (`id_Clasifica_Calif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabla que contiene la información de las bases de datos del archivo JSON';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `mydb`.`T_Clasifica_Calif` (`id_Clasifica_Calif`, `clasifica_calif`) VALUES ('1', 'High');
INSERT INTO `mydb`.`T_Clasifica_Calif` (`id_Clasifica_Calif`, `clasifica_calif`) VALUES ('2', 'Medium');
INSERT INTO `mydb`.`T_Clasifica_Calif` (`id_Clasifica_Calif`, `clasifica_calif`) VALUES ('3', 'Low');
INSERT INTO `mydb`.`T_Clasifica_Calif` (`id_Clasifica_Calif`, `clasifica_calif`) VALUES ('4', 'Sin informacion');
